language: generic

matrix:
    include:
        - env: TRAVIS_PYTHON_VERSION=3.6
          os: linux
          dist: trusty
          services: docker
          sudo: required
        - env: TRAVIS_PYTHON_VERSION=3.5
          os: linux
          dist: trusty
          services: docker
          sudo: required
        - env: TRAVIS_PYTHON_VERSION=3.4
          os: linux
          dist: trusty
          services: docker
          sudo: required
        - env: TRAVIS_PYTHON_VERSION=3.3
          os: linux
          dist: trusty
          services: docker
          sudo: required
        - env: TRAVIS_PYTHON_VERSION=2.7
          os: linux
          dist: trusty
          services: docker
          sudo: required
        - os: osx


before_install: travis/before_install.sh
install: travis/install.sh
script: travis/script.sh
after_script: travis/after_script.sh
after_success: travis/after_success.sh
after_failure: travis/after_failure.sh
