language: python

addons:
  apt:
    packages:
    - freetds-dev

matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
          python: 2.6
        - os: linux
          dist: trusty
          sudo: required
          python: 2.7
        - os: linux
          dist: trusty
          sudo: required
          python: 3.3
        - os: linux
          dist: trusty
          sudo: required
          python: 3.4
        - os: linux
          dist: trusty
          sudo: required
          python: 3.5
        # Use generic language for osx
        - os: osx
          language: generic

# Travis-ci doesn't support Python on OS X. Install it manually for now.
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install freetds; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi

install:
    - pip install .

# No tests currently, as those require a running instance of SQL Server.
script: true
